---
- name: install mysql
  apt:
    name={{item}}
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create user for mysql with all right
  mysql_user:
    name={{ database_username }}
    password={{ database_password }}
    priv='*.*:ALL,GRANT'
    host="%"
    state=present
  notify:
    - restart mysql

- name: Enable remote connections
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^(bind-address*)"
    replace: '# \1'
  notify:
    - restart mysql
